services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Receivables/Dockerfile
    ports:
      - "5282:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db; Database=receivables_db; User Id=sa; Password=Password1; TrustServerCertificate=True;
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: .
      dockerfile: DockerFileDb
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: Password1
      ACCEPT_EULA: Y